import PlanetMark from './PlanetMark';
import type { Language, Step } from './algorithms';

export default function ChessView({ step, language }: { step: Step; language: Language }) {
  const v = step.variables; const ko = language === 'ko'; const n = Number(v.n);
  if (v.mode === 'knight') {
    const moves: number[][] = JSON.parse(String(v.moves));
    return <div className="chess-view"><p className="frontier">N = {n} <strong data-testid="puzzle-result">{ko ? '방문' : 'Visited'}: {v.count} / {n * n}</strong>{step.type === 'done' && <span>{v.result ? ko ? '여행 성공' : 'Tour found' : ko ? '경로 없음' : 'No tour'}</span>}</p><table className="chess-board" aria-label={ko ? '기사의 방문 순서' : 'Knight visit order'}><tbody>{Array.from({ length: n }, (_, row) => <tr key={row}>{Array.from({ length: n }, (_, column) => { const order = moves.findIndex((position) => position[0] === row && position[1] === column); return <td key={column} className={(row + column) % 2 ? 'dark-square' : ''} style={order === moves.length - 1 && order >= 0 ? { outline: '2px solid #d9a446', outlineOffset: '-2px' } : undefined}>{order >= 0 && <div className="chess-beacon"><svg viewBox="-20 -20 40 40" aria-hidden="true"><PlanetMark r={14} fill={order === moves.length - 1 ? '#d6b476' : '#8faf9d'} /></svg><span style={{ fontSize: 14 }}>{order + 1}{order === moves.length - 1 && ' ♞'}</span></div>}</td>; })}</tr>)}</tbody></table><p className="frontier">{moves.length ? moves.map((position) => `(${position.join(',')})`).join(' → ') : ko ? '가능한 경로 없음' : 'No possible path'}</p></div>;
  }
  const positions: (number[] | null)[] = JSON.parse(String(v.positions));
  return <div className="chess-view"><p className="frontier">N = {n} <strong data-testid="puzzle-result">{ko ? '해' : 'Solutions'}: {v.count}</strong></p><table className="chess-board" aria-label={ko ? '퀸 배치와 현재 검사 칸' : 'Queen positions and current candidate'}><tbody>{Array.from({ length: n }, (_, row) => <tr key={row}>{Array.from({ length: n }, (_, column) => <td key={column} className={(row + column) % 2 ? 'dark-square' : ''} style={row === Number(v.row) && column === Number(v.column) && step.type !== 'done' ? { outline: '2px solid #d9a446', outlineOffset: '-2px' } : undefined}>{positions.some((position) => position && position[0] === row && position[1] === column) ? <div className="chess-beacon"><svg viewBox="-20 -20 40 40" aria-hidden="true"><PlanetMark r={14} fill="#8faf9d" /></svg><span>♛</span></div> : step.type === 'check' && row === Number(v.row) && column === Number(v.column) ? v.safe ? '·' : '×' : ''}</td>)}</tr>)}</tbody></table>{step.type === 'done' && <div className="collection-results">{(JSON.parse(String(v.solutions)) as number[][][]).map((solution, index) => <div key={index}>#{index + 1}: [{solution.map((position) => position[1]).join(', ')}]</div>)}{!Number(v.count) && <span>{ko ? '가능한 배치 없음' : 'No valid placement'}</span>}</div>}</div>;
}
