import type { Language } from './algorithms';

// Catalog order. The precise explanation stays in each algorithm's summary.
export const lessonTaglines: Record<string, Record<Language, string>> = {
  // Sorting
  'bubble-sort': { ko: '옆자리 사람하고만 얘기해서 일을 끝내는 방법.', en: 'Getting things done by talking only to your neighbor.' },
  'selection-sort': { ko: '제일 작은 것부터 하나씩 데려옵니다.', en: 'Bring over the smallest one. Then the next.' },
  'insertion-sort': { ko: '늦게 왔어도, 자기 자리는 있습니다.', en: 'Arriving late doesn’t mean you can’t find your place.' },
  'merge-sort': { ko: '각자 정리하고, 나중에 모이면 됩니다.', en: 'Tidy up separately. Meet again later.' },
  'quick-sort': { ko: '기준 하나 세우면, 양쪽 사정이 좀 달라집니다.', en: 'Pick a pivot. Things look different on either side.' },
  'shell-sort': { ko: '멀리 있는 것부터 대충 맞춰봅니다.', en: 'Start with the distant pairs. Close the gaps later.' },
  'heap-sort': { ko: '맨 위에 있는 것부터 내려보냅니다.', en: 'Send down whoever is at the top.' },
  'counting-sort': { ko: '비교하기 귀찮으면, 몇 개인지 세면 됩니다.', en: 'If comparing feels like a chore, try counting.' },
  'radix-sort': { ko: '숫자 전체를 보기엔, 한 자리로도 바쁩니다.', en: 'One digit at a time is quite enough to deal with.' },
  'bucket-sort': { ko: '비슷한 것끼리 담아두면, 나중이 좀 편합니다.', en: 'Put similar things together. It helps later.' },
  // Searching
  'linear-search': { ko: '처음부터 하나씩. 성실한 것도 방법입니다.', en: 'One by one, from the beginning. Persistence counts.' },
  'binary-search': { ko: '절반은 안 봐도 된다는 확신.', en: 'The confidence to leave half of it unseen.' },
  'jump-search': { ko: '몇 칸 건너뛰고, 지나쳤으면 돌아옵니다.', en: 'Skip a few places. Come back if you went too far.' },
  'interpolation-search': { ko: '있을 법한 자리를 먼저 짚어봅니다.', en: 'Start where it seems likely to be.' },
  // Graphs
  'breadth-first-search': { ko: '깊이 들어가기 전에, 주변부터 둘러봅니다.', en: 'Look around before going any deeper.' },
  'depth-first-search': { ko: '일단 끝까지 가보고 생각하는 편.', en: 'The sort who goes all the way before reconsidering.' },
  'dijkstra': { ko: '덜 먼 곳부터 가다 보면, 길이 좀 보입니다.', en: 'Start with the nearer places. A route begins to emerge.' },
  'bellman-ford': { ko: '좋은 소식이 있으면, 거리도 다시 고칩니다.', en: 'When better news arrives, update the distances.' },
  'floyd-warshall': { ko: '거길 거쳐 가면 더 가까울지도 모릅니다.', en: 'It might be shorter if you go through there.' },
  'prim': { ko: '아는 곳에서 한 군데씩 더 연결합니다.', en: 'From familiar ground, connect one more place.' },
  'kruskal': { ko: '싼 연결부터. 빙빙 돌게 되면 빼고요.', en: 'Take the cheaper links. Skip the ones that make a loop.' },
  'topological-sort': { ko: '양말부터 신고 신발을 신는 정도의 순서.', en: 'The kind of order that puts socks before shoes.' },
  'detect-cycle': { ko: '어쩐지, 아까 왔던 곳 같습니다.', en: 'This feels suspiciously like somewhere we’ve been.' },
  'articulation-points': { ko: '그 사람 빠지면 모임이 갈라지는 경우.', en: 'Sometimes one person is holding the group together.' },
  'bridges': { ko: '이 연결 하나가 생각보다 중요했습니다.', en: 'That one connection mattered more than it looked.' },
  'eulerian-path': { ko: '모든 길을 한 번씩. 욕심은 그 정도만.', en: 'Every road, exactly once. That’s ambition enough.' },
  'hamiltonian-path': { ko: '모든 곳에 한 번씩 들르기는 꽤 까다롭습니다.', en: 'Visiting every place once is surprisingly awkward.' },
  'strongly-connected-components': { ko: '서로 오갈 수 있는 사이끼리 묶어둡니다.', en: 'Group the places that can all reach one another.' },
  'travelling-salesman': { ko: '다 들러야 한다면, 덜 돌아가는 쪽으로.', en: 'If you have to visit them all, take fewer detours.' },
  // Data structures
  'stack': { ko: '방금 한 일부터 되돌리는 편.', en: 'Start undoing with the thing you just did.' },
  'queue': { ko: '먼저 온 사람부터. 별다른 사정은 없습니다.', en: 'First to arrive, first to leave. Nothing personal.' },
  'linked-list': { ko: '다음 사람 연락처만 알고 있어도 됩니다.', en: 'Knowing how to reach the next person is enough.' },
  'doubly-linked-list': { ko: '다음 사람도, 이전 사람도 알고 있습니다.', en: 'Keep in touch with the next person and the previous one.' },
  'min-heap': { ko: '제일 작은 건 늘 위에 둡니다.', en: 'Keep the smallest one within reach.' },
  'max-heap': { ko: '제일 큰 건 늘 위에 둡니다.', en: 'Keep the largest one within reach.' },
  'priority-queue': { ko: '줄은 섰지만, 급한 사람이 먼저입니다.', en: 'There’s a queue, but the urgent ones go first.' },
  'binary-search-tree': { ko: '작으면 왼쪽, 크면 오른쪽. 대화는 짧게.', en: 'Smaller to the left, larger to the right. Keep it brief.' },
  'avl-tree': { ko: '한쪽으로 기울면, 자세를 고쳐 앉습니다.', en: 'When things lean too far, readjust the posture.' },
  'red-black-tree': { ko: '색깔에 관한 몇 가지 약속으로 균형을 잡습니다.', en: 'A few rules about color keep things balanced.' },
  'trie': { ko: '말문이 같은 단어들은 같이 출발합니다.', en: 'Words that start alike set off together.' },
  'fenwick-tree': { ko: '필요한 합만 챙겨두는 작은 장부.', en: 'A small ledger that keeps just the sums you need.' },
  'segment-tree': { ko: '구간마다 담당자를 둬봤습니다.', en: 'Give each stretch someone to look after it.' },
  'hash-table': { ko: '이름을 주소로 바꾸면 찾기가 좀 쉽습니다.', en: 'Turn a name into an address. Finding it gets easier.' },
  'disjoint-set': { ko: '같은 편인지 확인하고, 아니면 합쳐봅니다.', en: 'Check if they’re on the same side. Join them if not.' },
  'bloom-filter': { ko: '없다는 건 확실한데, 있다는 건 글쎄요.', en: 'Definitely absent. Possibly present. That’s the deal.' },
  'graph-structure': { ko: '점 몇 개와, 그 사이의 사정들.', en: 'A few dots, and the connections between them.' },
  'deque': { ko: '앞문도 뒷문도 열어뒀습니다.', en: 'Both the front and the back doors are open.' },
  'lru-cache': { ko: '한동안 안 찾은 것부터 자리를 비웁니다.', en: 'Make room by letting go of what hasn’t been used lately.' },
  // Strings
  'naive-search': { ko: '한 글자씩 맞춰봅니다. 별다른 요령 없이.', en: 'Match one letter at a time. No particular tricks.' },
  'kmp': { ko: '틀렸다고, 아는 것까지 잊을 필요는 없습니다.', en: 'A mismatch doesn’t mean forgetting what you already know.' },
  'z-search': { ko: '처음과 얼마나 닮았는지 적어둡니다.', en: 'Write down how much each part resembles the beginning.' },
  'rabin-karp': { ko: '지문부터 대조하고, 닮았으면 자세히 봅니다.', en: 'Compare fingerprints first. Look closer when they match.' },
  'hamming-distance': { ko: '같은 자리에서 다른 글자만 세어봅니다.', en: 'Count the letters that differ in the same positions.' },
  'longest-common-substring': { ko: '둘 사이에 끊기지 않고 겹치는 말.', en: 'The longest bit they share without interruption.' },
  'regular-expression-matching': { ko: '정확한 글자 대신, 이런 모양이면 됩니다.', en: 'It doesn’t need the exact letters. Just this pattern.' },
  'palindrome': { ko: '반대쪽에서 읽어도 같은 이야기.', en: 'The same story, even from the other end.' },
  // Dynamic programming
  'lcs': { ko: '중간에 빠진 건 있어도, 순서는 같았습니다.', en: 'Some bits are missing, but the order is still the same.' },
  'edit-distance': { ko: '얼마나 고치면 같은 말이 될까요.', en: 'How much editing would make these say the same thing?' },
  'knapsack': { ko: '다 가져가고 싶지만, 가방은 이만합니다.', en: 'You’d like to take it all. The bag has other ideas.' },
  // Mathematics
  'bits': { ko: '켜고 끄는 것만으로도 할 일이 꽤 많습니다.', en: 'There’s plenty to do with just on and off.' },
  'factorial': { ko: '하나씩 줄여 곱했을 뿐인데, 벌써 이만큼.', en: 'Multiply down one by one, and suddenly it’s this big.' },
  'fibonacci': { ko: '앞의 둘을 더했을 뿐인데, 이야기가 길어집니다.', en: 'Just add the previous two. The story keeps growing.' },
  'primality-test': { ko: '나눠 들어갈 사람이 있는지 찾아봅니다.', en: 'See if anyone else divides into it.' },
  'euclidean-algorithm': { ko: '남은 것끼리 다시 나누다 보면.', en: 'Keep dividing with what remains.' },
  'least-common-multiple': { ko: '서로 다른 주기가 다시 만나는 때.', en: 'When two different rhythms meet again.' },
  'sieve-of-eratosthenes': { ko: '배수들을 지우고 나니, 남는 얼굴들.', en: 'Cross out the multiples. See who’s left.' },
  'is-power-of-two': { ko: '둘씩 불려서 여기까지 왔는지 봅니다.', en: 'Check whether doubling brought it all the way here.' },
  'pascal-triangle': { ko: '윗자리 둘을 더하면, 다음 줄이 됩니다.', en: 'Add the two above. Another row takes shape.' },
  'integer-partition': { ko: '같은 숫자도 여러 방식으로 나눠 담습니다.', en: 'There’s more than one way to split up the same number.' },
  'liu-hui': { ko: '각을 더할수록, 원에 조금 가까워집니다.', en: 'Add more sides. Get a little closer to a circle.' },
  'binary-floating-point': { ko: '컴퓨터도 소수를 딱 떨어지게 말하진 못합니다.', en: 'Even a computer can’t always say a decimal exactly.' },
  'prime-factors': { ko: '더는 나눌 수 없는 재료까지 풀어봅니다.', en: 'Break it down to the ingredients that won’t split further.' },
  'complex-number': { ko: '숫자에 방향 하나가 더 생겼습니다.', en: 'Numbers found another direction to go in.' },
  'radian': { ko: '각도를 재는데, 원의 길이를 빌려봅니다.', en: 'Borrow a circle’s arc to measure an angle.' },
  'fast-powering': { ko: '같은 곱셈을 매번 처음부터 할 필요는 없죠.', en: 'No need to repeat every multiplication from scratch.' },
  'horner-method': { ko: '길게 쓴 식을, 안쪽부터 차곡차곡.', en: 'Fold a long expression neatly from the inside out.' },
  'matrix': { ko: '행과 열이 만나면, 곱하고 더할 일이 생깁니다.', en: 'A row meets a column. There’s multiplying and adding to do.' },
  'euclidean-distance': { ko: '둘 사이가 얼마나 먼지, 곧장 재봅니다.', en: 'Measure how far apart they are, straight across.' },
  'square-root': { ko: '일단 짐작하고, 조금씩 고쳐봅니다.', en: 'Make a guess. Improve it a little at a time.' },
  'fourier-transform': { ko: '겹쳐 들리던 것들을 주파수별로 풀어봅니다.', en: 'Untangle what you heard into its frequencies.' },
  // Sets and combinations
  'cartesian-product': { ko: '이쪽 하나, 저쪽 하나. 가능한 짝은 전부.', en: 'One from here, one from there. Every possible pair.' },
  'fisher-yates': { ko: '한 자리씩 바꿔보면, 꽤 공평하게 섞입니다.', en: 'Swap one place at a time. A fair shuffle takes shape.' },
  'power-set': { ko: '고르거나 말거나. 그것도 전부 경우의 수.', en: 'Take it or leave it. Count every possibility.' },
  'permutations': { ko: '누가 앞에 서느냐도 경우의 수에 넣습니다.', en: 'Who stands where is part of the possibilities.' },
  'combinations': { ko: '순서는 됐고, 누가 같이 가는지만 봅니다.', en: 'Never mind the order. Who’s going together?' },
  'longest-increasing-subsequence': { ko: '중간은 건너뛰어도, 조금씩 커지는 흐름.', en: 'Skip a few things. Keep the growing thread.' },
  'shortest-common-supersequence': { ko: '둘의 순서를 지키면서, 한 줄로 합칩니다.', en: 'Bring two sequences together without upsetting their order.' },
  'maximum-subarray': { ko: '이어진 구간 중, 합이 제일 괜찮았던 때.', en: 'The stretch where the numbers added up best.' },
  'combination-sum': { ko: '어떻게 모아야 딱 그만큼 될까요.', en: 'What would add up to just that much?' },
  // Traversal
  'tree-depth-first-search': { ko: '가지 하나 끝까지 보고, 다음 가지로.', en: 'Follow one branch to its end. Then try the next.' },
  'tree-breadth-first-search': { ko: '같은 층부터 둘러보고 내려갑니다.', en: 'Look around the current floor before going down.' },
  'linked-list-traversal': { ko: '다음 사람이 알려주는 다음 사람.', en: 'The next person points you to the next person.' },
  'linked-list-reverse-traversal': { ko: '끝까지 갔다가, 돌아오면서 인사합니다.', en: 'Go to the end. Say hello on the way back.' },
  // Ciphers, learning, images and chance
  'polynomial-hash': { ko: '글자들을 숫자 하나로 접어둡니다.', en: 'Fold the letters into a single number.' },
  'rail-fence-cipher': { ko: '글자는 그대로, 앉는 줄만 바꿔봤습니다.', en: 'The same letters, sitting in different rows.' },
  'caesar-cipher': { ko: '알파벳을 몇 칸 옆으로 밀어봤습니다.', en: 'Nudge the alphabet a few places sideways.' },
  'hill-cipher': { ko: '글자를 묶어 행렬에 한번 통과시킵니다.', en: 'Bundle the letters and send them through a matrix.' },
  'knn': { ko: '가까운 이웃들의 의견을 들어봅니다.', en: 'See what the nearby neighbors think.' },
  'k-means': { ko: '가까운 쪽에 모이고, 중심도 다시 옮깁니다.', en: 'Gather nearby. Move the center. Try again.' },
  'seam-carving': { ko: '덜 눈에 띄는 길을 따라, 사진을 조금 줄입니다.', en: 'Follow a less noticeable path to make the image narrower.' },
  'weighted-random': { ko: '운에도 비중이 있습니다.', en: 'Even chance has its weights.' },
  // Other small puzzles
  'hanoi-tower': { ko: '옮기는 건 간단한데, 횟수는 그렇지 않습니다.', en: 'Moving a disc is simple. The number of moves isn’t.' },
  'square-matrix-rotation': { ko: '자리는 그대로 두고, 안의 것만 돌려봅니다.', en: 'Keep the frame. Turn what’s inside.' },
  'jump-game': { ko: '갈 수 있는 데까지 가면, 끝도 닿을까요.', en: 'If you go as far as you can, will you reach the end?' },
  'unique-paths': { ko: '오른쪽이나 아래로만 가도, 길은 여럿입니다.', en: 'Only right or down, and still so many ways to get there.' },
  'rain-terraces': { ko: '낮은 곳이라고 다 물이 고이진 않습니다.', en: 'Not every low spot gets to keep the rain.' },
  'n-queens': { ko: '서로 눈치 볼 일 없는 자리를 찾습니다.', en: 'Find everyone a place where they won’t threaten each other.' },
  'knight-tour': { ko: '이렇게 움직여서 모든 칸에 들를 수 있을까요.', en: 'Can those unusual moves take you to every square?' },
  'recursive-staircase': { ko: '한 칸, 두 칸. 올라가는 방법도 여러 가지.', en: 'One step, two steps. More than one way up.' },
  'best-time-to-buy-sell-stocks': { ko: '지나간 가격을 보면, 좋은 때가 보입니다.', en: 'Looking back at prices makes the good timing easier to spot.' },
  'valid-parentheses': { ko: '열었으면 닫고, 나중에 연 것부터.', en: 'Close what you opened. Most recent first.' },
};
