import PlanetMark from './PlanetMark';
import FourierView from './FourierView';
import type { Language, Step } from './algorithms';

export default function MathView({ step, language }: { step: Step; language: Language }) {
  const ko = language === 'ko';
  const v = step.variables;
  if (v.mode === 'fourier') return <FourierView step={step} language={language} />;
  if (v.mode !== 'bits') return <div className="math-view">
    {['complex', 'liu', 'radian', 'distance'].includes(String(v.mode)) && <p className="math-expression">{String(v.expression ?? '')}</p>}
    {v.mode === 'matrix-product' && <div><p className="math-expression">{String(v.expression)}</p><div className="matrix-product">{[['A', v.inputA], ['B', v.inputB], [ko ? 'C · 누적 합' : 'C · cumulative sums', v.output]].map(([label, serialized], matrixIndex) => <table className="graph-table" key={String(label)}><caption>{String(label)}</caption><tbody>{(JSON.parse(String(serialized)) as number[][]).map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j} className={matrixIndex === 0 && i === Number(v.row) && j === Number(v.k) || matrixIndex === 1 && i === Number(v.k) && j === Number(v.column) ? 'dependency-cell' : matrixIndex === 2 && i === Number(v.row) && j === Number(v.column) ? 'active-cell' : ''}>{value}</td>)}</tr>)}</tbody></table>)}</div></div>}
    {v.mode === 'sieve' && <div className="bucket-grid sieve-grid" role="list" aria-label={ko ? '소수 체' : 'Prime sieve'}>{(JSON.parse(String(v.isPrime)) as boolean[]).map((candidate, number) => <div role="listitem" key={number} className={`bucket-cell ${!candidate ? 'composite-number' : (JSON.parse(String(v.primes)) as number[]).includes(number) ? 'prime-number' : ''} ${v.current === number ? 'active-bucket' : ''}`} aria-label={`${number}: ${!candidate ? ko ? '제외' : 'excluded' : (JSON.parse(String(v.primes)) as number[]).includes(number) ? ko ? '소수' : 'prime' : ko ? '후보' : 'candidate'}`}><strong>{number}</strong></div>)}</div>}
    {v.mode === 'radian' && <svg className="complex-plane" viewBox="-120 -120 240 240" role="img" aria-label={ko ? `${v.degree}도 방향 · 단위원` : `Unit circle direction at ${v.degree} degrees`}><circle r="90" fill="none" stroke="#526b60" /><line x1="-100" y1="0" x2="100" y2="0" stroke="#526b60" /><line x1="0" y1="-100" x2="0" y2="100" stroke="#526b60" /><polyline points={Array.from({ length: 41 }, (_, i) => { const angle = (Number(v.radian) % (2 * Math.PI)) * i / 40; return `${45 * Math.cos(angle)},${-45 * Math.sin(angle)}`; }).join(' ')} fill="none" stroke="#d6b476" strokeWidth="3" /><line x1="0" y1="0" x2={90 * Math.cos(Number(v.radian))} y2={-90 * Math.sin(Number(v.radian))} stroke="#8faf9d" strokeWidth="2" /><PlanetMark cx={90 * Math.cos(Number(v.radian))} cy={-90 * Math.sin(Number(v.radian))} r="4" fill="#8faf9d" /><text x="76" y="14" fontSize="12" fill="#a3b0a7">0°</text></svg>}
    {(v.mode === 'complex' || v.mode === 'distance' && v.dimensions === 2) && <svg className="complex-plane" viewBox="-120 -120 240 240" role="img" aria-label={v.mode === 'distance' ? ko ? '두 점 사이 선분' : 'Segment between two points' : ko ? '복소평면 · 실수축과 허수축' : 'Complex plane · real and imaginary axes'}><line x1="-108" y1="0" x2="108" y2="0" stroke="#526b60" /><line x1="0" y1="-108" x2="0" y2="108" stroke="#526b60" /><text x="93" y="14" fontSize="10" fill="#a3b0a7">{v.mode === 'distance' ? 'x' : 'Re'}</text><text x="5" y="-100" fontSize="10" fill="#a3b0a7">{v.mode === 'distance' ? 'y' : 'Im'}</text>{v.mode === 'distance' && <line x1={(JSON.parse(String(v.points)) as number[][])[0][0] / Number(v.scale) * 100} y1={-(JSON.parse(String(v.points)) as number[][])[0][1] / Number(v.scale) * 100} x2={(JSON.parse(String(v.points)) as number[][])[1][0] / Number(v.scale) * 100} y2={-(JSON.parse(String(v.points)) as number[][])[1][1] / Number(v.scale) * 100} stroke="#d6b476" strokeWidth="2" />}{(JSON.parse(String(v.points)) as [number, number, string][]).map(([real, imaginary, label], index) => <g key={label}>{v.mode === 'complex' && <line x1="0" y1="0" x2={real / Number(v.scale) * 100} y2={-imaginary / Number(v.scale) * 100} stroke={index === 2 ? '#d6b476' : '#8faf9d'} strokeDasharray={index === 2 ? undefined : '3 3'} />}<PlanetMark cx={real / Number(v.scale) * 100} cy={-imaginary / Number(v.scale) * 100} r="3" fill={index === 2 ? '#d6b476' : '#8faf9d'} /><text x={real / Number(v.scale) * 100 + 5} y={-imaginary / Number(v.scale) * 100 + (index === 2 ? 12 : -5)} fontSize="10" fill="var(--space-ink, #e2e7d9)">{label === 'result' ? ko ? '결과' : 'result' : label}</text></g>)}</svg>}
    {v.mode === 'float'  && <div className="float-fields">{[[ko ? '부호 · 1비트' : 'Sign · one bit', String(v.binary).slice(0, 1), 'sign'], [ko ? '지수 · 8비트' : 'Exponent · eight bits', String(v.binary).slice(1, 9), 'exponent'], [ko ? '가수 · 23비트' : 'Fraction · 23 bits', String(v.binary).slice(9), 'fraction']].map(([label, binary, phase]) => <div key={phase}><span>{label}</span><div className="float-bits" role="list" aria-label={label}>{binary.split('').map((bit, index) => <strong key={index} role="listitem" className={step.type === phase ? 'active-bit' : ''}>{bit}</strong>)}</div></div>)}</div>}
    {v.mode === 'liu'  && <svg className="liu-circle" viewBox="-1.15 -1.15 2.3 2.3" role="img" aria-label={ko ? `단위원과 내접 ${v.sides}각형` : `Unit circle with inscribed ${v.sides}-gon`}><circle r="1" fill="none" stroke="#526b60" strokeWidth="0.015" /><polygon points={Array.from({ length: Number(v.sides) }, (_, i) => `${Math.cos(i * 2 * Math.PI / Number(v.sides))},${Math.sin(i * 2 * Math.PI / Number(v.sides))}`).join(' ')} fill="#82968c" stroke="#8faf9d" strokeWidth="0.012" /><line x1="0" y1="0" x2="1" y2="0" stroke="#d6b476" strokeWidth="0.012" /><text x="0.42" y="-0.04" fontSize="0.12" fill="#0b1012">r = 1</text></svg>}
    {v.mode === 'pascal'  && <div className="string-scroll"><div className="pascal-triangle" role="list" aria-label={ko ? '파스칼 삼각형' : 'Pascal triangle'}>{(JSON.parse(String(v.triangle)) as number[][]).map((row, rowIndex) => <div className="string-row" role="listitem" key={rowIndex} aria-label={`${ko ? '행' : 'Row'} ${rowIndex}`}>{row.map((value, column) => <div className={`string-cell ${step.type !== 'done' && rowIndex === Number(v.row) && column === Number(v.column ?? 0) ? 'current-character' : ''} ${step.type === 'add' && rowIndex === Number(v.row) - 1 && (column === Number(v.column) || column === Number(v.column) - 1) ? 'matched-character' : ''}`} key={column}><strong>{value}</strong></div>)}</div>)}</div></div>}
    {!['complex', 'liu', 'radian', 'matrix-product', 'distance'].includes(String(v.mode)) && <p className="math-expression">{String(v.expression ?? '')}</p>}
    {v.cells && <table className="graph-table"><caption>{ko ? '현재 계산 상태' : 'Current computation state'}</caption><thead><tr><th>{ko ? '변수' : 'Variable'}</th><th>{ko ? '값' : 'Value'}</th></tr></thead><tbody>{(JSON.parse(String(v.cells ?? '[]')) as [string, string | number][]).map(([label, value]) => <tr key={label}><th>{label}</th><td>{String(value)}</td></tr>)}</tbody></table>}
    {v.mode === 'power' && <div className="frontier">{ko ? '호출 스택 · 지수' : 'Call stack · exponents'} <strong>{String(v.stack)}</strong></div>}
    {v.mode === 'primality' && <table className="graph-table"><caption>{ko ? '검사한 약수와 나머지' : 'Tested divisors and remainders'}</caption><thead><tr><th>{ko ? '약수 후보' : 'Divisor candidate'}</th><th>{ko ? '나머지' : 'Remainder'}</th></tr></thead><tbody>{(JSON.parse(String(v.checks)) as number[][]).map(([divider, remainder]) => <tr key={divider} className={divider === Number(v.divider) ? 'active-row' : undefined}><td>{divider}</td><td>{remainder}</td></tr>)}</tbody></table>}
    {['fibonacci', 'factors', 'horner', 'root'].includes(String(v.mode)) && <div className="string-scroll"><div className="string-row" role="list" aria-label={v.mode === 'root' ? ko ? '제곱근 추정 이력' : 'Root estimate history' : v.mode === 'horner' ? ko ? '다항식 계수' : 'Polynomial coefficients' : v.mode === 'factors' ? ko ? '누적 소인수' : 'Accumulated prime factors' : ko ? '현재 피보나치 수열' : 'Current Fibonacci sequence'}>{(JSON.parse(String(v.sequence)) as number[]).map((value, index) => <div key={index} role="listitem" className={`string-cell ${index === Number(v.index ?? v.n) ? 'current-character' : ''}`} style={{ minWidth: `${Math.max(36, String(value).length * 8 + 12)}px` }}><small>{index}</small><strong>{v.mode === 'root' ? Number(value.toPrecision(6)) : value}</strong></div>)}</div></div>}
    {'result' in v && <div className="frontier">{ko ? '결과' : 'Result'} <output data-testid="math-result">{String(v.result)}</output></div>}
  </div>;
  const width = Math.max(8, Number(v.number).toString(2).length, Number(v.result).toString(2).length);
  const rows = [[ko ? '입력' : 'Input', Number(v.number)], [ko ? '결과' : 'Result', Number(v.result)]] as const;
  return <div className="math-view">
    <p>{ko ? `비트 ${v.position} 선택 · 오른쪽부터 0 · ${step.type === 'start' || step.type === 'done' ? '원래 입력' : step.type}` : `Selected bit ${v.position} · zero from the right · ${step.type === 'start' || step.type === 'done' ? 'original input' : step.type}`}</p>
    <div className="string-scroll">{rows.map(([label, value]) => <div key={label}>
      <div className="frontier"><span>{label}</span><strong>{value}</strong></div>
      <div className="string-row" role="list" aria-label={label} style={{ minWidth: width * 36 }}>
        {value.toString(2).padStart(width, '0').split('').map((bit, index) => <div role="listitem" key={index} className={`string-cell ${width - index - 1 === Number(v.position) ? 'current-character' : ''}`}><small>{width - index - 1}</small><strong>{bit}</strong></div>)}
      </div>
    </div>)}</div>
    {step.type === 'done' && <table className="graph-table"><caption>{ko ? '같은 입력에 적용한 각 연산의 결과' : 'Independent results for the same input'}</caption><thead><tr><th>{ko ? '연산' : 'Operation'}</th><th>{ko ? '십진수' : 'Decimal'}</th><th>{ko ? '이진수' : 'Binary'}</th></tr></thead><tbody>{Object.entries(JSON.parse(String(v.results))).map(([name, value]) => <tr key={name}><th>{name}</th><td>{Number(value)}</td><td>{Number(value).toString(2)}</td></tr>)}</tbody></table>}
  </div>;
}
