import PlanetMark from './PlanetMark';
import type { Language, Step } from './algorithms';

export default function WeightedView({ step, language }: { step: Step; language: Language }) {
  const v = step.variables; const ko = language === 'ko';
  const rows: [string, number][] = JSON.parse(String(v.rows));
  const cumulative: number[] = JSON.parse(String(v.cumulative));
  let left = 0;
  return <div><svg viewBox="0 0 360 230" className="weight-intervals" role="img" aria-label={ko ? '가중치별 궤도 구간과 추첨 위치' : 'Weighted orbital intervals and draw position'}>{rows.map(([name, weight], index) => { const start = left; left += weight; const angle = (start + weight / 2) / Number(v.total) * Math.PI * 2 - Math.PI / 2; return <g key={index}><circle cx="180" cy="112" r="72" fill="none" stroke={index === Number(v.current) ? '#d6b476' : index % 2 ? '#8faf9d' : '#82968c'} strokeWidth="12" pathLength={Number(v.total)} strokeDasharray={`${weight} ${Number(v.total) - weight}`} strokeDashoffset={-start} transform="rotate(-90 180 112)" opacity={weight > 0 ? 1 : 0} /><title>{`${name}: ${weight}`}</title>{weight > 0 && <text x={180 + Math.cos(angle) * 93} y={116 + Math.sin(angle) * 93} textAnchor="middle" fontSize="12" fill="#e2e7d9">{index}</text>}</g>; })}<PlanetMark cx={180} cy={112} r={23} fill="#82968c" />{'randomNumber' in v && <line x1="180" y1="112" x2={180 + Math.cos(Number(v.u) * Math.PI * 2 - Math.PI / 2) * 80} y2={112 + Math.sin(Number(v.u) * Math.PI * 2 - Math.PI / 2) * 80} stroke="#d6b476" strokeWidth="2" />}<text x="180" y="218" textAnchor="middle" fontSize="11" fill="#a3b0a7">{ko ? '전체 가중치' : 'Total weight'}: {v.total}</text></svg><p className="frontier">u = {v.u} · r = {'randomNumber' in v ? Number(Number(v.randomNumber).toFixed(4)) : '—'} <strong data-testid="weighted-result">{step.type === 'done' ? v.result : '—'}</strong></p><table className="graph-table"><caption>{ko ? '항목별 확률과 누적 구간' : 'Item probabilities and cumulative intervals'}</caption><thead><tr><th>#</th><th>{ko ? '항목' : 'Item'}</th><th>{ko ? '확률' : 'Probability'}</th><th>{ko ? '누적합' : 'Cumulative'}</th></tr></thead><tbody>{rows.map(([name, weight], index) => <tr key={index} className={index === Number(v.current) ? 'active-row' : ''}><td>{index}</td><td>{name}</td><td>{Number((weight / Number(v.total) * 100).toFixed(2))}%</td><td>{cumulative[index] ?? '—'}</td></tr>)}</tbody></table></div>;
}
