import type { Language, Step } from './algorithms';

export default function WeightedView({ step, language }: { step: Step; language: Language }) {
  const v = step.variables; const ko = language === 'ko';
  const rows: [string, number][] = JSON.parse(String(v.rows));
  const cumulative: number[] = JSON.parse(String(v.cumulative));
  let left = 0;
  return <div><svg viewBox="0 0 360 100" className="weight-intervals" role="img" aria-label={ko ? '가중치 구간과 추첨 위치' : 'Weight intervals and draw position'}>{rows.map(([name, weight], index) => { const start = left; left += weight; return <g key={index}><rect x={10 + start / Number(v.total) * 340} y="25" width={weight / Number(v.total) * 340} height="40" fill={index === Number(v.current) ? '#e3b768' : index % 2 ? '#b6cfc0' : '#d9e5dc'} stroke="#fff" /><title>{name}: {weight}</title>{weight > 0 && <text x={10 + (start + weight / 2) / Number(v.total) * 340} y="50" textAnchor="middle" fontSize="11" fill="#22382b">{index}</text>}</g>; })}{'randomNumber' in v && <path d={`M${10 + Number(v.u) * 340} 10v65`} stroke="#203d2c" strokeWidth="2" />}<text x="10" y="92" fontSize="11">0</text><text x="350" y="92" textAnchor="end" fontSize="11">{v.total}</text></svg><p className="frontier">u = {v.u} · r = {'randomNumber' in v ? Number(Number(v.randomNumber).toFixed(4)) : '—'} <strong data-testid="weighted-result">{step.type === 'done' ? v.result : '—'}</strong></p><table className="graph-table"><caption>{ko ? '항목별 확률과 누적 구간' : 'Item probabilities and cumulative intervals'}</caption><thead><tr><th>#</th><th>{ko ? '항목' : 'Item'}</th><th>{ko ? '확률' : 'Probability'}</th><th>{ko ? '누적합' : 'Cumulative'}</th></tr></thead><tbody>{rows.map(([name, weight], index) => <tr key={index} className={index === Number(v.current) ? 'active-row' : ''}><td>{index}</td><td>{name}</td><td>{Number((weight / Number(v.total) * 100).toFixed(2))}%</td><td>{cumulative[index] ?? '—'}</td></tr>)}</tbody></table></div>;
}
